### ISSUE TITLE
Losen importlib-metedata requirement

### ISSUE THREAD

**Issue by asbfall** [ansys/pyensight#315]
### 📝 Description of the feature

The current pyensight requires `importlib-metadata>=4.0,<5`
Since we want to use this library in a solution based on SAF, we have dependencies conflicts with opentelemetry-api (1.18.0) that requires importlib-metadata >= 6.0.0

![image](https://github.com/ansys/pyensight/assets/96308874/0572fcc3-7bed-481c-a7e5-48cf464dfb51)

Is there a known issue that motivates a strong constraint on importlib-metadata?

**Comment by mariostieriansys** [comment]
Hi @asbfall .
Sorry for coming to you only now, for some reasons I didn't get notified about it.
This hard constraint was introduced during the tech review process of the package.
Since it is only being used for identifying the version of PyEnSight and do the switch of the documentation on github, it should be probably ok for us to loosen it.

I will look into that and keep you posted.

Mario

**Comment by mariostieriansys** [comment]
@asbfall I have queued a build of a new release, v.0.6.1, which solves this issue.
Should be ready soon

**Comment by asbfall** [comment]
Hello @mariostieriansys That's great. I'll test this new package. Many thanks
