### ISSUE TITLE
ensight python code for a finite cutting plane not working as expected

### ISSUE THREAD

**Issue by amscosta** [ansys/pyensight#425]
Hi All,
I am trying to use a python script to programmatically generate finite clip planes attached to a spline. Unfortunatelly,
it is not working as expected (see the attached image). Wondering if an expert can show me the fix. The piece of code for
the clip plane of the attached image is:
ensight.part.select_begin(20,12,1)
ensight.clip.begin()
ensight.clip.type("mesh")
ensight.clip.extents("finite")
ensight.clip.tool("plane")
ensight.clip.spline_id(0)
ensight.clip.spline_location(0.5)
ensight.clip.end()
ensight.clip.create()

Any expert advice is highly apreciated.
![to_forum](https://github.com/user-attachments/assets/843631c3-5d8b-46ce-b822-fcb74a51fef6)

**Comment by mariostieriansys** [comment]
Hi @amscosta,
I believe the issue is that the clip you selected is still a "plane" clip, so while you might be able to update the plane location to the spline location you've selected, the clip will still "cut" the parent where the plane is located; since the plane still cuts the location on the right, you will still get the "unwanted" cut included. The issue in not specific to your code but rather related to the kind of cut you are trying to do.

What I would do, in EnSight, is this:

1) Split the "parent" in two parts. This is possible adding a plane just at the middle of it, and use an inside/outside intersect clip, which will create respectively the left/right portion of the parent. You can so virtually split the fluid zone in two parts
2) Create two splines, one in the first portion, one in the second portion
3) Create the plane-following-spline clips selecting as parent one of the two portions and the relevant spline.

In this way you will be sure that you are cutting only one portion of the fluid zone, removing the "not wanted" cut

You could potentially run these operations manually in EnSight, copy the code and convert it into Python code, and use it in PyEnSight if required.

Hope it helps

**Comment by kecolburn** [comment]
On other aspect to check is the SIZE of the plane tool. When in "Finite mode" withe clip, the size of the plane tool matters. It may be large enough to clip the other portion of the geometry (unwanted). Reducing the size of the plane tool to be only 25% larger than the intended region should help.

**Comment by amscosta** [comment]
Thank guys for the output.
Is the SIZE keyword a variable ? how can I modify that?

**Comment by kecolburn** [comment]
Please reference the PyEnSight Documentation. That particular Plane tool control is listed here : https://ensight.docs.pyansys.com/version/stable/_autosummary/ansys.api.pyensight.ens_tool_plane.ENS_TOOL_PLANE.html#ansys.api.pyensight.ens_tool_plane.ENS_TOOL_PLANE
